---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

if (not lib.is_server) then

    ---@class lib.ui
    lib.ui = {};

    ---@class Panel
    lib.ui.Panel = {};

    ---@class Window
    lib.ui.Window = {};

    lib.ui.Enum = require 'lib.ui.components.Enum';
    lib.ui.PlaySound = require 'lib.ui.components.Audio';

    lib.ui.EnumHeritage = require 'lib.ui.components.EnumHeritage';
    lib.ui.RenderRectangle = require 'lib.ui.components.rectangle';
    lib.ui.RenderSprite = require 'lib.ui.components.sprite';
    lib.ui.RenderText = require 'lib.ui.components.text';

    lib.ui.BadgeStyle = require 'lib.ui.menu.elements.ItemsBadge';
    lib.ui.Colour = require 'lib.ui.menu.elements.ItemsColour';
    lib.ui.PanelColour = require 'lib.ui.menu.elements.PanelColour';

    ---@class UIItems: BaseObject
    UIItems = lib.class.singleton("UIItems", function(class)
        return class;
    end);

    ---@class UIPanels: BaseObject
    UIPanels = lib.class.singleton("UIPanels", function(class)
        return class;
    end);

    require 'lib.ui.menu.items.UIButton';
    require 'lib.ui.menu.items.UICheckBox';
    require 'lib.ui.menu.items.UIInfo';
    require 'lib.ui.menu.items.UILine';
    require 'lib.ui.menu.items.UIList';
    require 'lib.ui.menu.items.UISeparator';
    require 'lib.ui.menu.items.UISlider';
    require 'lib.ui.menu.items.UISliderHeritage';
    require 'lib.ui.menu.items.UISliderProgress';

    require 'lib.ui.menu.panels.UIBoutonPanel';
    require 'lib.ui.menu.panels.UIColourPanel';
    require 'lib.ui.menu.panels.UIGridPanel';
    require 'lib.ui.menu.panels.UIInfoPanel';
    require 'lib.ui.menu.panels.UIPercentagePanel';
    require 'lib.ui.menu.panels.UISpritPanel';
    require 'lib.ui.menu.panels.UIStatisticsPanel';

    require 'lib.ui.menu.windows.UIHeritage';

    require 'lib.ui.menu.MenuController';
    require 'lib.ui.menu.Menu';

    require 'lib.ui.menu.index';

    lib.ui.visual = require 'lib.ui.components.visual';

end

return lib.ui;