---@enum lib.ui.EnumHeritage
return {

    Parent1 = {

        "female_0",
        "female_1",
        "female_2",
        "female_3",
        "female_4",
        "female_5",
        "female_6",
        "female_7",
        "female_8",
        "female_9",
        "female_10",
        "female_11",
        "female_12",
        "female_13",
        "female_14",
        "female_15",
        "female_16",
        "female_17",
        "female_18",
        "female_19",
        "female_20",
        "special_female_0",

        "male_0",
        "male_1",
        "male_2",
        "male_3",
        "male_4",
        "male_5",
        "male_6",
        "male_7",
        "male_8",
        "male_9",
        "male_10",
        "male_11",
        "male_12",
        "male_13",
        "male_14",
        "male_15",
        "male_16",
        "male_17",
        "male_18",
        "male_19",
        "male_20",
        "special_male_0",
        "special_male_1",
        "special_male_2",

    },

    Parent2 = {

        "male_0",
        "male_1",
        "male_2",
        "male_3",
        "male_4",
        "male_5",
        "male_6",
        "male_7",
        "male_8",
        "male_9",
        "male_10",
        "male_11",
        "male_12",
        "male_13",
        "male_14",
        "male_15",
        "male_16",
        "male_17",
        "male_18",
        "male_19",
        "male_20",
        "special_male_0",
        "special_male_1",
        "special_male_2",

        "female_0",
        "female_1",
        "female_2",
        "female_3",
        "female_4",
        "female_5",
        "female_6",
        "female_7",
        "female_8",
        "female_9",
        "female_10",
        "female_11",
        "female_12",
        "female_13",
        "female_14",
        "female_15",
        "female_16",
        "female_17",
        "female_18",
        "female_19",
        "female_20",
        "special_female_0",

    };

};